name: Pi dtoverlay checks

on:
  pull_request:
    paths:
      - 'arch/**'
      - 'block/**'
      - 'certs/**'
      - 'crypto/**'
      - 'drivers/**'
      - 'fs/**'
      - 'include/**'
      - 'init/**'
      - 'io_uring/**'
      - 'ipc/**'
      - 'kernel/**'
      - 'lib/**'
      - 'mm/**'
      - 'net/**'
      - 'rust/**'
      - 'scripts/**'
      - 'security/**'
      - 'sound/**'
      - 'tools/**'
      - 'usr/**'
      - 'virt/**'
      - 'Kbuild'
      - 'Kconfig'
      - 'Makefile'
    branches: [ "main" ]
  push:
    paths:
      - 'arch/**'
      - 'block/**'
      - 'certs/**'
      - 'crypto/**'
      - 'drivers/**'
      - 'fs/**'
      - 'include/**'
      - 'init/**'
      - 'io_uring/**'
      - 'ipc/**'
      - 'kernel/**'
      - 'lib/**'
      - 'mm/**'
      - 'net/**'
      - 'rust/**'
      - 'scripts/**'
      - 'security/**'
      - 'sound/**'
      - 'tools/**'
      - 'usr/**'
      - 'virt/**'
      - 'Kbuild'
      - 'Kconfig'
      - 'Makefile'
    branches: [ "main" ]
  workflow_dispatch:

env:
  UTILS_DIR: "${{github.workspace}}/utils"

jobs:
  dtoverlaycheck:
    runs-on: ubuntu-latest

    steps:
    - name: Install toolchain
      run: |
        sudo apt update
        sudo apt-get install gcc-arm-linux-gnueabihf libfdt-dev device-tree-compiler
      timeout-minutes: 10

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        clean: true

    - name: overlaycheck
      run: |
        git clone https://github.com/raspberrypi/utils ${{env.UTILS_DIR}}
        cd ${{env.UTILS_DIR}}
        pwd
        mkdir build
        cd build
        pwd
        cmake ..
        make -j4
        sudo make install
        cd ${{github.workspace}}
        pwd
        make ARCH=arm KERNEL=kernel CROSS_COMPILE=arm-linux-gnueabihf- bcm2711_defconfig
        make ARCH=arm KERNEL=kernel CROSS_COMPILE=arm-linux-gnueabihf- dtbs
        ${{env.UTILS_DIR}}/overlaycheck/overlaycheck
